spring:
  profiles:
    active: @PROFILE@
  application:
    name: imethan-blog-2
    description: imethan blog base springboot .
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/resources/templates
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/imethan_blog_2
    rest:
      basePath: /hal
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


