server:
  port: 8778
mongodb:
  uri: mongodb://imethan:imethan123456@192.168.9.224:27017/imethan_blog_3

#以下配置为了安全考虑，当前配置写入到数据库里面，以下配置不生效
mail:
  host: smtp.qq.com #发送邮件服务器
  username: ethanwong@qq.com #发送邮件的邮箱地址
  password: password    #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
  properties.mail.smtp.port: 465 #端口号465或587
  from: ethanwong@qq.com # 发送邮件的地址，和上面username一致可以任意
qiniu:
  accessKey: accessKey
  secretKey: secretKey
  bucket: imethan-blog-2
  domainOfBucket: domainOfBucket