spring:
  profiles:
    active: @PROFILE@
  application:
    name: imethan-blog-2
    description: imethan blog base springboot .
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/resources/templates
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/imethan_blog_3
      gridfs:
        bucket: blog_fs
    rest:
      basePath: /hal
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core: DEBUG
#      mongodb:
#        driver:
#          protocol: DEBUG

