server:
  port: 80
mail:
  host: smtp.qq.com #发送邮件服务器
  username: ethanwong@qq.com #发送邮件的邮箱地址
  password: password  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
  properties.mail.smtp.port: 465 #端口号465或587
  from: ethanwong@qq.com # 发送邮件的地址，和上面username一致可以任意
mongodb:
  uri: mongodb://127.0.0.1:27017/imethan_blog_4
qiniu:
  accessKey: accessKey
  secretKey: secretKey
  bucket: imethan-blog-2
  domainOfBucket: http://qmyn9dpl5.hn-bkt.clouddn.com